version: '3.8'

services:
  kingshare-marketplace:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: kingshare-marketplace
    restart: unless-stopped
    ports:
      - 3002:3002
    volumes:
      - /app/node_modules
      - ./:/app
